<?php
/**
 * Theme creation / file writing / activation helpers.
 *
 * Backs the studio/create-theme, studio/write-theme-file, and
 * studio/activate-theme abilities. Path traversal is prevented by:
 *
 *   1. Validating slugs against `^[a-z0-9][a-z0-9-]*$` at the schema level.
 *   2. Sanitizing each segment of the relative file path with `sanitize_file_name`.
 *   3. Re-resolving with `realpath()` and asserting the resolved path stays
 *      under the resolved themes root.
 *
 * @package StudioAgent
 */

defined( 'ABSPATH' ) || exit;

class Studio_Agent_Theme_Tools {

	/**
	 * Create a new block theme skeleton on disk.
	 *
	 * @param array<string,mixed> $args
	 * @return array|WP_Error
	 */
	/**
	 * Render the file map for a new theme without touching disk.
	 *
	 * Public so the preview ability can stage the same files we would write
	 * during create_theme(), without actually writing them.
	 *
	 * @param array<string,mixed> $args
	 * @return array{slug:string,name:string,files:array<string,string>}|WP_Error
	 */
	public static function render_theme_files( $args ) {
		$args = is_array( $args ) ? $args : array();

		$slug = self::validate_slug( $args['slug'] ?? '' );
		if ( is_wp_error( $slug ) ) {
			return $slug;
		}

		$name        = trim( (string) ( $args['name'] ?? '' ) );
		$description = trim( (string) ( $args['description'] ?? 'A theme generated by the Studio Agent.' ) );
		$author      = trim( (string) ( $args['author'] ?? 'Studio Agent' ) );
		$background  = self::validate_hex( (string) ( $args['background'] ?? '#ffffff' ), '#ffffff' );
		$foreground  = self::validate_hex( (string) ( $args['foreground'] ?? '#000000' ), '#000000' );
		$accent      = self::validate_hex( (string) ( $args['accent']     ?? '#3858e9' ), '#3858e9' );

		if ( '' === $name ) {
			return new WP_Error( 'studio_theme_invalid_name', 'Theme name is required.' );
		}

		return array(
			'slug'  => $slug,
			'name'  => $name,
			'files' => array(
				'style.css'             => self::style_css( $slug, $name, $description, $author ),
				'theme.json'            => self::theme_json( $background, $foreground, $accent ),
				'templates/index.html'  => self::index_template(),
				'parts/header.html'     => self::header_part(),
				'parts/footer.html'     => self::footer_part( $name ),
			),
		);
	}

	public static function create_theme( $args ) {
		$rendered = self::render_theme_files( $args );
		if ( is_wp_error( $rendered ) ) {
			return $rendered;
		}

		$slug  = $rendered['slug'];
		$files = $rendered['files'];

		$theme_dir = self::theme_dir_for( $slug );
		if ( is_dir( $theme_dir ) ) {
			return new WP_Error(
				'studio_theme_exists',
				sprintf( 'A theme directory already exists at %s. Pick a different slug or use studio/write-theme-file to update it.', $theme_dir )
			);
		}

		if ( ! wp_mkdir_p( $theme_dir ) ) {
			return new WP_Error( 'studio_theme_mkdir_failed', 'Could not create the theme directory.' );
		}

		$written = array();
		foreach ( $files as $relative => $content ) {
			$result = self::write_file_inside( $slug, $relative, $content );
			if ( is_wp_error( $result ) ) {
				return $result;
			}
			$written[] = $relative;
		}

		// Refresh theme cache so wp_get_theme() picks up the new entry on the next call.
		wp_clean_themes_cache();

		// Pre-flight validation. WP_Theme::errors() catches malformed style.css
		// headers and missing parent themes. Rollback if anything fails so we
		// don't leave a broken theme on disk.
		$errors = self::validate_theme( $slug );
		if ( ! empty( $errors ) ) {
			self::remove_theme_dir( $theme_dir );
			wp_clean_themes_cache();
			return new WP_Error(
				'studio_theme_validation_failed',
				'Theme failed validation; rolled back. ' . implode( ' | ', $errors ),
				array( 'errors' => $errors )
			);
		}

		return array(
			'theme_slug'    => $slug,
			'theme_dir'     => $theme_dir,
			'files_created' => $written,
			'admin_url'     => admin_url( 'themes.php' ),
			'note'          => 'Theme created and validated. Call studio/activate-theme with theme_slug to switch to it.',
		);
	}

	/**
	 * Lightweight pre-flight checks. Returns a list of human-readable error
	 * strings; empty list = OK. This catches the common breakage modes
	 * (broken style.css headers, invalid theme.json, missing parent theme)
	 * without spinning up a separate Playground.
	 *
	 * @return list<string>
	 */
	private static function validate_theme( string $slug ): array {
		$errors = array();

		$theme = wp_get_theme( $slug );
		if ( ! $theme->exists() ) {
			$errors[] = 'wp_get_theme() does not see the theme — likely a malformed style.css header.';
			return $errors;
		}
		if ( $theme->errors() ) {
			foreach ( (array) $theme->errors()->get_error_messages() as $message ) {
				$errors[] = (string) $message;
			}
		}

		$theme_json_path = self::theme_dir_for( $slug ) . '/theme.json';
		if ( file_exists( $theme_json_path ) ) {
			$contents = file_get_contents( $theme_json_path );
			$decoded  = json_decode( (string) $contents, true );
			if ( null === $decoded && JSON_ERROR_NONE !== json_last_error() ) {
				$errors[] = 'theme.json is not valid JSON: ' . json_last_error_msg();
			}
		}

		return $errors;
	}

	private static function remove_theme_dir( string $dir ): void {
		if ( ! is_dir( $dir ) ) {
			return;
		}
		$iterator = new RecursiveIteratorIterator(
			new RecursiveDirectoryIterator( $dir, FilesystemIterator::SKIP_DOTS ),
			RecursiveIteratorIterator::CHILD_FIRST
		);
		foreach ( $iterator as $path ) {
			$path->isDir() ? rmdir( $path->getPathname() ) : unlink( $path->getPathname() );
		}
		rmdir( $dir );
	}

	/**
	 * Write a single file inside an existing theme directory.
	 *
	 * @param array<string,mixed> $args
	 * @return array|WP_Error
	 */
	public static function write_file( $args ) {
		$args = is_array( $args ) ? $args : array();

		$slug = self::validate_slug( $args['theme_slug'] ?? '' );
		if ( is_wp_error( $slug ) ) {
			return $slug;
		}

		if ( ! is_dir( self::theme_dir_for( $slug ) ) ) {
			return new WP_Error( 'studio_theme_not_found', sprintf( 'Theme "%s" does not exist. Create it first with studio/create-theme.', $slug ) );
		}

		$relative = (string) ( $args['file_path'] ?? '' );
		$content  = (string) ( $args['content'] ?? '' );

		$result = self::write_file_inside( $slug, $relative, $content );
		if ( is_wp_error( $result ) ) {
			return $result;
		}

		return array(
			'theme_slug' => $slug,
			'written'    => $relative,
			'full_path'  => $result,
			'bytes'      => strlen( $content ),
		);
	}

	/**
	 * Activate a theme by slug.
	 *
	 * @param array<string,mixed> $args
	 * @return array|WP_Error
	 */
	public static function activate_theme( $args ) {
		$args = is_array( $args ) ? $args : array();

		$slug = self::validate_slug( $args['theme_slug'] ?? '' );
		if ( is_wp_error( $slug ) ) {
			return $slug;
		}

		$theme = wp_get_theme( $slug );
		if ( ! $theme->exists() ) {
			return new WP_Error( 'studio_theme_not_found', sprintf( 'Theme "%s" does not exist.', $slug ) );
		}

		$previous = (string) get_option( 'stylesheet' );
		switch_theme( $slug );

		return array(
			'active_theme'   => $slug,
			'previous_theme' => $previous,
			'preview_url'    => home_url( '/' ),
			'admin_url'      => admin_url( 'themes.php' ),
		);
	}

	// ---------- internals ----------

	private static function validate_slug( $slug ) {
		$slug = is_string( $slug ) ? trim( $slug ) : '';
		if ( '' === $slug || ! preg_match( '/^[a-z0-9][a-z0-9-]*$/', $slug ) ) {
			return new WP_Error( 'studio_theme_invalid_slug', 'Slug must match /^[a-z0-9][a-z0-9-]*$/ — lowercase, alphanumeric and dashes only.' );
		}
		return $slug;
	}

	private static function validate_hex( string $value, string $fallback ): string {
		$value = trim( $value );
		return preg_match( '/^#[0-9a-fA-F]{6}$/', $value ) ? $value : $fallback;
	}

	private static function theme_dir_for( string $slug ): string {
		return rtrim( get_theme_root(), '/\\' ) . '/' . $slug;
	}

	/**
	 * Writes content to <theme>/<relative>, asserting the resolved path stays
	 * inside the theme directory. Returns the absolute path on success.
	 *
	 * @return string|WP_Error
	 */
	private static function write_file_inside( string $slug, string $relative, string $content ) {
		$relative = trim( $relative );
		if ( '' === $relative ) {
			return new WP_Error( 'studio_theme_invalid_path', 'file_path is required.' );
		}
		if ( str_contains( $relative, "\0" ) ) {
			return new WP_Error( 'studio_theme_invalid_path', 'file_path contains a null byte.' );
		}

		// Normalize separators and reject absolute / traversal paths.
		$relative = str_replace( '\\', '/', $relative );
		$relative = ltrim( $relative, '/' );
		$segments = array();
		foreach ( explode( '/', $relative ) as $segment ) {
			if ( '' === $segment || '.' === $segment ) {
				continue;
			}
			if ( '..' === $segment ) {
				return new WP_Error( 'studio_theme_invalid_path', 'file_path may not contain ".." segments.' );
			}
			$clean = sanitize_file_name( $segment );
			if ( '' === $clean ) {
				return new WP_Error( 'studio_theme_invalid_path', sprintf( 'Path segment "%s" is not a valid filename.', $segment ) );
			}
			$segments[] = $clean;
		}
		if ( empty( $segments ) ) {
			return new WP_Error( 'studio_theme_invalid_path', 'file_path is empty after sanitization.' );
		}

		$theme_dir = self::theme_dir_for( $slug );
		$full      = $theme_dir . '/' . implode( '/', $segments );
		$dir       = dirname( $full );

		if ( ! wp_mkdir_p( $dir ) ) {
			return new WP_Error( 'studio_theme_mkdir_failed', sprintf( 'Could not create directory %s', $dir ) );
		}

		// Final guard: realpath of the parent dir must live under the theme root.
		$resolved_dir   = realpath( $dir );
		$resolved_theme = realpath( $theme_dir );
		if ( false === $resolved_dir || false === $resolved_theme || ! str_starts_with( $resolved_dir, $resolved_theme ) ) {
			return new WP_Error( 'studio_theme_path_escape', 'Resolved path falls outside the theme directory.' );
		}

		$bytes = file_put_contents( $full, $content );
		if ( false === $bytes ) {
			return new WP_Error( 'studio_theme_write_failed', sprintf( 'Failed writing %s', $full ) );
		}

		return $full;
	}

	// ---------- skeleton content ----------

	private static function style_css( string $slug, string $name, string $description, string $author ): string {
		$name        = wp_strip_all_tags( $name );
		$description = wp_strip_all_tags( $description );
		$author      = wp_strip_all_tags( $author );

		return <<<CSS
/*
Theme Name: {$name}
Theme URI: https://example.com/{$slug}
Author: {$author}
Description: {$description}
Version: 1.0.0
Requires at least: 6.5
Requires PHP: 7.4
License: GPL-2.0-or-later
License URI: https://www.gnu.org/licenses/gpl-2.0.html
Text Domain: {$slug}
*/
CSS;
	}

	private static function theme_json( string $background, string $foreground, string $accent ): string {
		$schema = array(
			'\$schema' => 'https://schemas.wp.org/trunk/theme.json',
			'version'  => 3,
			'settings' => array(
				'appearanceTools' => true,
				'color'           => array(
					'palette' => array(
						array( 'slug' => 'background', 'color' => $background, 'name' => 'Background' ),
						array( 'slug' => 'foreground', 'color' => $foreground, 'name' => 'Foreground' ),
						array( 'slug' => 'accent',     'color' => $accent,     'name' => 'Accent' ),
					),
				),
				'layout'          => array(
					'contentSize' => '720px',
					'wideSize'    => '1100px',
				),
				'typography'      => array(
					'fluid' => true,
				),
			),
			'styles'   => array(
				'color'    => array(
					'background' => 'var(--wp--preset--color--background)',
					'text'       => 'var(--wp--preset--color--foreground)',
				),
				'elements' => array(
					'link' => array(
						'color' => array( 'text' => 'var(--wp--preset--color--accent)' ),
					),
				),
				'spacing'  => array(
					'padding' => array(
						'top'    => '2rem',
						'right'  => '1.5rem',
						'bottom' => '2rem',
						'left'   => '1.5rem',
					),
				),
			),
			'templateParts' => array(
				array( 'name' => 'header', 'title' => 'Header', 'area' => 'header' ),
				array( 'name' => 'footer', 'title' => 'Footer', 'area' => 'footer' ),
			),
		);

		// Re-escape the $schema key after json_encode (it gets stripped by PHP heredoc).
		$json = wp_json_encode( $schema, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES );
		return str_replace( '"\\$schema"', '"$schema"', (string) $json );
	}

	private static function index_template(): string {
		return <<<HTML
<!-- wp:template-part {"slug":"header","tagName":"header"} /-->

<!-- wp:group {"tagName":"main","layout":{"type":"constrained"}} -->
<main class="wp-block-group">
	<!-- wp:query {"queryId":1,"query":{"perPage":10,"pages":0,"offset":0,"postType":"post","order":"desc","orderBy":"date","author":"","search":"","exclude":[],"sticky":"","inherit":true}} -->
	<div class="wp-block-query">
		<!-- wp:post-template -->
		<!-- wp:post-title {"isLink":true} /-->
		<!-- wp:post-date /-->
		<!-- wp:post-excerpt /-->
		<!-- /wp:post-template -->

		<!-- wp:query-pagination -->
		<!-- wp:query-pagination-previous /-->
		<!-- wp:query-pagination-numbers /-->
		<!-- wp:query-pagination-next /-->
		<!-- /wp:query-pagination -->

		<!-- wp:query-no-results -->
		<!-- wp:paragraph -->
		<p>No posts yet.</p>
		<!-- /wp:paragraph -->
		<!-- /wp:query-no-results -->
	</div>
	<!-- /wp:query -->
</main>
<!-- /wp:group -->

<!-- wp:template-part {"slug":"footer","tagName":"footer"} /-->
HTML;
	}

	private static function header_part(): string {
		return <<<HTML
<!-- wp:group {"tagName":"header","layout":{"type":"constrained"}} -->
<header class="wp-block-group">
	<!-- wp:site-title /-->
	<!-- wp:site-tagline /-->
</header>
<!-- /wp:group -->
HTML;
	}

	private static function footer_part( string $theme_name ): string {
		$year = (int) gmdate( 'Y' );
		$theme_name = wp_strip_all_tags( $theme_name );
		return <<<HTML
<!-- wp:group {"tagName":"footer","layout":{"type":"constrained"}} -->
<footer class="wp-block-group">
	<!-- wp:paragraph {"align":"center"} -->
	<p class="has-text-align-center">© {$year} — Powered by {$theme_name}.</p>
	<!-- /wp:paragraph -->
</footer>
<!-- /wp:group -->
HTML;
	}
}
